import numpy as np
import json
import os

class GenericProblem:
    """
    Generic Optimization Problem Setup.
    Loads BCs and Loads from a 'pipeline_bcs.json' file generated by the orchestrator.
    """
    def __init__(self, bc_file="pipeline_bcs.json"):
        self.name = "GenericHybrid"
        self.bc_file = bc_file
        
    def apply(self, nodes):
        """
        Reads BCs from JSON.
        Format expected:
        {
          "fixed_nodes": [id1, id2, ...],
          "load_nodes": [id3, id4, ...],
          "load_vector": [docx, docy, docz]
        }
        """
        # Search for BC file in CWD or up one level
        path = self.bc_file
        if not os.path.exists(path):
            path = os.path.join("..", self.bc_file)
            
        if not os.path.exists(path):
            print(f"[GenericProblem] Warning: BC file '{self.bc_file}' not found. No BCs applied!")
            return {}, {}
            
        with open(path, 'r') as f:
            data = json.load(f)
            
        fixed_ids = set(data.get("fixed_nodes", []))
        load_ids = set(data.get("load_nodes", []))
        load_vec = data.get("load_vector", [0.0, -1.0, 0.0])
        
        # Build BC dict
        bcs = {}
        for idx in fixed_ids:
            if idx < len(nodes):
                bcs[idx] = [0, 1, 2, 3, 4, 5] # Fix All 6 DOFs
                
        # Build Loads dict
        loads = {}
        # Distribute load among all load_nodes (divide total force)
        num_loads = len(load_ids)
        if num_loads > 0:
            force_per_node = [f / num_loads for f in load_vec]
            load_6d = force_per_node + [0, 0, 0]
            
            for idx in load_ids:
                if idx < len(nodes):
                    loads[idx] = load_6d
                    
        print(f"[GenericProblem] Applied BCs: {len(bcs)} fixed, {len(loads)} loaded (Force={load_vec})")
        return loads, bcs
